### ISSUE TITLE
BUG (severe) checking other player balance crashes game

### ISSUE THREAD

**Issue by jpcsupplies** [jpcsupplies/Economy_mod#11]
Cant see where its going out of bounds, its either the for count or the records count being retained from the /bal somehow.  I've added an extra count=0; in case thats the issue but theres not a  lot that can go wrong..   

Steps to reproduce - run game.  type /bal  should give debug info all good
now try /bal bob 
splat.

here's what the log tells me -

2015-08-27 02:53:49.856 - Thread:   1 ->  Exception occured: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Economy.EconomyScript.processMessage(String messageText)
   at Economy.EconomyScript.gotMessage(String messageText, Boolean& sendToOthers)
   at Sandbox.Game.Gui.MyGuiScreenChat.HandleInput(Boolean receivedFocusInThisUpdate)
   at Sandbox.Graphics.GUI.MyScreenManager.HandleInput()
   at Sandbox.Graphics.GUI.MyDX9Gui.HandleInput()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.FixedRenderLoop.<>c__DisplayClass2.<Run>b__1()
   at Sandbox.Engine.Platform.GenericRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.FixedRenderLoop.Run(VoidAction tickCallback)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at SpaceEngineers.MyProgram.RunInternal(String[] args)
   at SpaceEngineers.MyProgram.Main(String[] args)
2015-08-27 02:53:49.858 - Thread:   1 ->  Hiding window
2015-08-27 02:53:50.338 - Thread:   1 ->  Hiding window done
2015-08-27 02:53:50.338 - Thread:   1 ->  Showing message

**Comment by jpcsupplies** [comment]
The redesign by midspace rendered this bug a non-issue as the code with the issue is no longer used.

**Comment by SaltPepp** [comment]
Ill give screaming angels my code I have produced on the weekend so he can take bits and pieces out of it for the mod as I built my code to work outside of space engineers. I'm really busy at the moment. Sorry for any inconvenience.

Sent from my Windows Phone
________________________________

**Comment by jpcsupplies** [comment]
ahh there you are toby;  guess you lost the tangentspy login;  install the github windows client and build your code into a repository  in saltpepp and we can cherry pick off that;  Or when you are in next, use the github there and slap it on under mine; and add yourself as contributor
Going by Midspace's code, they look to be quite highly skilled; make me look like a simpleton! ha

**Comment by SaltPepp** [comment]
I've got repos under my name but they are private repos as I've got a upgraded github account.

Sent from my Windows Phone
________________________________

**Comment by midspace** [comment]
If you just have code chunks that you are unsure of, you can put into pastebin.com, and paste the link here.
That'll allow any of us to disseminate it at our leisure.

Yeah, we've been tooling with .Net since it was first released in 2002.

Me, I'm an old hand at Microwold Basic, QBasic, QuickBasic (My Doom Save file editor was in Quick Basic, with graphics splash screen and mouse).
I started web programming University and Java Script, before they taught us C.
Did one of my major Physics projects using Visual Basic 3 front end, with a C library as the back end, because VB3 sucked space balls trying to do physics calculations.
I always found C to be a better structured language, and C# was a natural step up.
Like Phoenix said, VB.Net is a very different beast. The way the code is expressed might seem similar to Visual Basic, but it's fully object oriented and is full compile, not the pseudo run-time that VB has.

I'd like for Keen to allow .vb, but we'll have to assume for the moment it's not happening soon and learn to love C#.

The things you have to remember:
C# is case sensitive.
.Net is a managed language. A lot of the things you might expect to write, are probably already written and expressed via some sort of method on a System class.
Keen have imposed limitations within Mods, so even if you find a good example on how to do something in C#, there is a good chance it won't be allowed exactly how it has been written and require adjustment.

**Comment by midspace** [comment]
Also, when dealing with source control (GitHub, CodePlex, TFS, Visual Source Safe, etc.), it actually works in our favour to break code down into separate classes, and have each class in a separate file.

The compiler, and the SE itself won't care if there are more classes or more files.
But separating it, will help us keep code modularized and prevent too many bruised toes and egos from checking in code that someone else might also be working on at the same time.

**Comment by SaltPepp** [comment]
I've been producing a set of apis e.g player api, selling api, inventory api, permission api, config api ect.... But I haven't done very much because of school vce being in the way

Sent from my Windows Phone
________________________________

**Comment by jpcsupplies** [comment]
I've got some of Toby's ref code here: 

https://github.com/jpcsupplies/Econ_API


It should shortly transfer to 

https://github.com/SaltPepp/Econ_API

**Comment by SaltPepp** [comment]
I'm really fascinated and impressed with your programming screaming angels. I've never had anyone impress me as much as you have. You had my eyes wide open when I was reading your code. When you see my code, if you could correct me at all it would be appreciated as I'm self taught c#. Well done!

Sent from my Windows Phone
________________________________

**Comment by SaltPepp** [comment]
That's very very very old code nathan. I haven't uploaded my latest code to cybernexus.biz yet. The zip that's on there is the very first bit of code I sent you ages ago.i have done allot since then. Ill be home around midnight tonight to continue programming. Ill upload my latest code to the web hosting account around midnight too

Sent from my Windows Phone
________________________________

**Comment by SaltPepp** [comment]
My current code for midspace to dissect is located at: http://saltpepp.github.io/Economy/
The repository is private.
- Toby

To: reply@reply.github.com
From: tangentspy@outlook.com
Subject: RE: [Economy_mod] BUG (severe) checking other player balance crashes game (#11)
Date: Fri, 4 Sep 2015 12:27:54 +1000







I've been producing a set of apis e.g player api, selling api, inventory api, permission api, config api ect.... But I haven't done very much because of school vce being in the way



Sent from my Windows Phone



From:
midspace

Sent:
‎4/‎09/‎2015 10:17 AM

To:
jpcsupplies/Economy_mod

Cc:
Toby Wilkinson

Subject:
Re: [Economy_mod] BUG (severe) checking other player balance crashes game (#11)





If you just have code chunks that you are unsure of, you can put into pastebin.com, and paste the link here.

That'll allow any of us to disseminate it at our leisure.

Yeah, we've been tooling with .Net since it was first released in 2002.

Me, I'm an old hand at Microwold Basic, QBasic, QuickBasic (My Doom Save file editor was in Quick Basic, with graphics splash screen and mouse).

I started web programming University and Java Script, before they taught us C.

Did one of my major Physics projects using Visual Basic 3 front end, with a C library as the back end, because VB3 sucked space balls trying to do physics calculations.

I always found C to be a better structured language, and C# was a natural step up.

Like Phoenix said, VB.Net is a very different beast. The way the code is expressed might seem similar to Visual Basic, but it's fully object oriented and is full compile, not the pseudo run-time that VB has.

I'd like for Keen to allow .vb, but we'll have to assume for the moment it's not happening soon and learn to love C#.

The things you have to remember:

C# is case sensitive.

.Net is a managed language. A lot of the things you might expect to write, are probably already written and expressed via some sort of method on a System class.

Keen have imposed limitations within Mods, so even if you find a good example on how to do something in C#, there is a good chance it won't be allowed exactly how it has been written and require adjustment.

—

Reply to this email directly or 
view it on GitHub.

**Comment by midspace** [comment]
I get 404 when accesing either
http://saltpepp.github.io/Economy/
or this
https://github.com/SaltPepp/Econ_API

Either there isn't anything there, or I don't have access.

**Comment by midspace** [comment]
SaltPepp commented 14 hours ago
> I'm really fascinated and impressed with your programming screaming angels. I've never had anyone impress me as much as you have. You had my eyes wide open when I was reading your code. When you see my code, if you could correct me at all it would be appreciated as I'm self taught c#. Well done!

I think the only formal education or training I did on a programming language was in C.
We all learnt C# and .Net on the job.
I'm kind of jealous of these days, as when I first self taught Basic, we didn't have internet. Had to read the manual and dissect existing programs.
And then when we starting out using C# .Net, there wasn't many online resources, because barely anyone knew the language. We had to buy some books that the Microsoft MVP's had published to learn anything.
Most of what I know now, is just 13 years of experience.
It'll come to you eventually (either that, or google it :) ).
