### ISSUE TITLE
/bal

### ISSUE THREAD

**Issue by TheEngineer50** [jpcsupplies/Economy_mod#128]
It does not appear to function on my server. Some other commands do. Just a heads up mate.

**Comment by jpcsupplies** [comment]
do you get a balance with /hud on 
 ?

**Comment by TheEngineer50** [comment]
Not sure, I'll check tomorrow but everyone on the server can type /bal and
it just shows up in chat, like the mod never sees it.

**Comment by jpcsupplies** [comment]
hmm wierd its working fine on our main test server ill try it in client mode and see if anything odd happens.

**Comment by jpcsupplies** [comment]
I get nothing wierd.

Could be your data has messed up somehow.  I have a report that sese saves the world in a funny way that sometimes messes up economy mod saves

**Comment by midspace** [comment]
If the mod caught an exception, it will be reported inside the `%appdata%\SpaceEngineers\Storage\EconomyClient.Log` file.

On the Server, a similar file will also be found, though its location will be dependant on your hosting provider.
`%appdata%\SpaceEngineers\Storage\EconomyServer.Log`.

**Comment by midspace** [comment]
@TheEngineer50 : are you using SESE by any chance, or some unusual game server configuration?

**Comment by midspace** [comment]
Found the problem.
I've posted this in our mod thread, but will repeat it here.

Apparently Scripts and Script Mod API are not running on Dedicated Service Instance.
It does *not* affect the Dedicated Server console (which appears as a black box with text).
This problem is know to KeenSWH at this time.
There isn't anything we as modders can do about it.
It's in Keen's hands. Hopefully there will be a hot fix tomorrow.

**Comment by TheEngineer50** [comment]
No, I was not using SESE. 

It is working now though.

**Comment by jpcsupplies** [comment]
we pushed out a minor update that assumed something was slowing our client server connects in the process of troubleshooting, which at least keeps the script up instead of desperately hoping the data is there and grabbing it without waiting when client is waiting for config data, this may ease the issue in some unusual scenarios where things connect in unusual ways.  But the main issue appears to be as midspace pointed out above which is beyond our control for some of the more obscure bugs being reported.

**Comment by midspace** [comment]
This should now be fixed with the latest updated from KeenSWH.
