### ISSUE TITLE
Find way to use worth command from another server mod/plugin.

### ISSUE THREAD

**Issue by foogs** [jpcsupplies/Economy_mod#191]
Find way to use worth command from another server mod/plugin. How?
need something

**Comment by jpcsupplies** [comment]
Hmm.. you could try duplicating the worth code in another mod of your own, ie
Have it read the pricing data from the data file.
Have it scan in the blocks and inventory of an item, to tally up the components used/stored
Have it add up the value of those components based on the pricing data you previously loaded.

Only downside to this approach is price changes to components since last server restart might not be current.

If this mod of your own also needs to generate transactions and payments, you can interact directly with economy to pay/bill players directly via our API here:
https://github.com/jpcsupplies/Economy_mod/tree/master/EconomyAPI
