### ISSUE TITLE
Torch.Eco "Compatibility"? Old or even outdated now?

### ISSUE THREAD

**Issue by X-Niter** [jpcsupplies/Economy_mod#201]
So Torch has a plugin called Torch Economy and torch economy market.
From finding the repo, it's been 2 years sense updates from what I could see. 

It's info said it uses and or works along with y'alls mod, but seems to just fail any time I attempt a server start up.
Would you guys know anything about the plugin?
If you do and it's considered "dead" then that's fine, I just wanted to get my facts straight and thought maybe sense this plugin works with y'alls mod, that you might have a better idea then my self. 

Thank you in advance! 

Also another thing, sense SE has some what of an Eco already, where does this come in?
I'm currently working to load it up and see what it's about, I'm just curious on how it plays with the already implemented eco in the base of the game.

Again, thank you in advance.

**Comment by jpcsupplies** [comment]
Not familiar with Torch.eco,  if it is 2 years old, then it likely misses a few things.  midspace did do some "play nice" work with frontier economy to work around some odd quirks we noticed running under torch.  The only issue you might have is the way torch (and for that matter the vanilla game now) unloads grids away from the player may cause strange things to happen with player owned trade zones attached to a beacon.

Frontier economy pre-dates keen economy and we had some influence over how keen economy evolved feature wise as we were in contact with the dev team while they were working out what to put in it.  The unfinished mission system in frontier economy for example directly inspired the mission types added into keen economy mission contracts as we gave the keen programmer working on that a copy of our mission definitions file.

The two economy systems can co-exist.     In frontier economy you can buy and sell "space credits" at any of our NPC trade station locations as a physical item at a fixed exchange rate (roughly 94:1 i think.. so one frontier credit buys in at about 94 keen space credits).         Then keen space credits can be deposited into the players account at any keen "ATM" blocks.     This allowed for the fun prospect that players transporting money between a Frontier and keen space station could get pirated and the money stolen.  There was also a special category added to frontier economy for the keen economy items. (refer "keen economy integration" section of our [manual ](https://steamcommunity.com/sharedfiles/filedetails/?id=481264606&preview=true).

The main differences are in frontier economy you can sell player owned ships, but not "magic up" encounter ships, while in keen economy they only allow ships to be purchased by " magic'ing up" ships from the encounter ship blueprints folder, but you cannot sell player owned ships.    We tried to argue the merits of being able to sell player ships - but the "fluffy bunny" argument that players might try to sell "trolling" ships to other players that were a bad deal scared them off it.   In practical use the "player ship selling" has been one of the best features in frontier economy.     Even a "bad deal" is often a pretty interesting shaped workspace for players to build onto. 

Also in our trade zones - open pricing offers remain until the trade zone owner black lists items they dont want to sell, or defined buying limits are hit - while in the keen economy you have to keep re-listing items manually as orders are filled.

Conversely, keens economy is a "super inflation" system - unlimited money - unlimited supplies drip fed out in small batches, where supply has a limited effect on price, meaning on a credit by credit basis, keen space credits are a lot less valuable than frontier economy credits (see 94:1 comment earlier)- although their base prices are losely based on processing overhead using a special graphical interface to trade.. valuing the keen ships vs frontier economics shows wildly inconsistent valuation of resources.     In frontier economy, there is a limited money supply - admins can effect this (and we actually recommend they do)  but in general to add more money, more players need to join the server and use their starting money in the economy to increase cash flow.   In keen economy, one player alone can get rich without playing multiplayer at all.   Our system is slightly more accurate in that on a server a "top 3%" can evolve who control large amounts of money - but equally exploits are only partially effective, as once a trade zone runs out of money they cant get anymore, unlike keen trade stations where every station has an unlimited supply of money.

Frontier economy is mainly driven by chat commands, although you can put up automatic price lists and other things onto LCD screens - the prices are directly effected by available stock, but maintains a safety margin with regard to price ceilings and floors so that exploitive buying/selling at the same station is unlikely to be as profitable as selling between stations.  Our prices work from a static value baseline for ores based roughly on average procedural distribution of ores in the game and manually tweaked for sanity.   In frontier economy it is possible as a server admin to directly tweak those baseline prices by editing their price table - or ban their trade entirely.  But equally if you have a run on something like say medical components it is also possible with scarity to make the sell price of medical components as a manufactured product to be worth a lot more than the ores and components that go into manufacturing them, giving players a strong profit incentive to start manufacturing them and selling them to trade zones - in keen economy what the station buys is often entirely random and such small inconsequental amounts players soon bore of trading.

**Comment by X-Niter** [comment]
Wow..
I will be very honest and say that this has been the most detailed and thorough response I've ever came across on github.
With that aside, thank you very kindly for getting me on track and in line with a very solid and detailed understanding of both Keen and Frontier eco and how the eco is driven. 
This will be a very eventful journey with y'alls mod and I'm excited to sit down and enjoy a more diverse and player-driven eco, as I've felt that the base one did not give enough dynamics when it came to limitation factors and player interaction.

I will go ahead and close this, but I would like to ask if you are okay with me sharing the knowledge and the word over to my group to allow them to also grasp the understanding? :) 

Thank you kindly jpcsupplies

**Comment by jpcsupplies** [comment]
Sure go ahead.    The manual for frontier economy goes into a fair amount of detail on the working features too where i've had a chance to explain it.  I think part of the reason frontier economy became popular was the detailed manual - can you imagine trying to work it out without instructions yikes! :)
